Improved documentation + small fix
GeyserMC/MCAuthLib pull request #14
Opened 2021-10-25 23:17 UTC by tycrek

Mostly improvements to the README (better formatting, more links/info).

Some lines in `pom.xml` switched from referencing `Steveice10/MCAuthLib` to `GeyserMC/MCAuthLib` because the old repository redirects here anyways, so the Maven info may as well have this updated information too.

Last thing: small fix in `HTTP.java`, I had to remove an unused `import` that was causing compilation to fail.

2021-10-26 10:18 UTC, rtm516 commented
The jitpack links can be replaced with the GeyserMC org as it seems to have a few builds done already
https://jitpack.io/#GeyserMC/MCAuthLib

2021-10-27 17:47 UTC, tycrek commented
Updated 👍

2021-11-07 13:34 UTC, rtm516 requested changes

2021-11-07 13:34 UTC, rtm516 commented on pom.xml
> +        <argLine/>
Gonna presume this wasn't meant to change, revert for a cleaner commit and makes it easier for people that need to change it later.
```suggestion
        <argLine></argLine>
```

2021-11-14 03:44 UTC, tycrek commented
Was fixed in 76fa778, not sure if GitHub sent any alerts for it (tried accepting changes from the app for the first time)

2022-01-13 03:59 UTC, tycrek commented
@rtm516 Able to re-review this one?

2022-02-12 15:18 UTC, rtm516 approved these changes

2023-10-26 22:55 UTC, closed without merging